name: Checks
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  PYTEST_ADDOPTS: --color=yes --pyargs watertap_contrib.reflo
  PIP_PROGRESS_BAR: "off"

jobs:

  linting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: psf/black@stable
        with:
          options: "--check --verbose"
          version: "~= 22.0"

  pytest:
    name: pytest (${{ matrix.os }}/${{ matrix.python-version }}/${{ matrix.install-mode }})
    runs-on: ${{ matrix.os-version }}
    needs: [linting]
    strategy:
      fail-fast: false
      matrix:
        python-version:
          - "3.8"
          - "3.9"
          - "3.10"
          - "3.11"
        os:
          - linux
          - win64
        install-mode:
          - editable
          - noneditable
        include:
          - os: linux
            os-version: ubuntu-latest
          - os: win64
            os-version: windows-latest
    steps:
      - uses: actions/checkout@v4
        if: matrix.install-mode == 'editable'
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install (editable)
        if: matrix.install-mode == 'editable'
        run: |
          pip install -r requirements-dev.txt
      - name: Set pip install ref for PR runs
        if: matrix.install-mode == 'noneditable' && github.event.pull_request
        shell: bash
        run: |
          echo "_pip_install_ref=${{ format('refs/pull/{0}/merge', github.event.pull_request.number) }}" >> $GITHUB_ENV
      - name: Set pip install ref for non-PR runs
        if: matrix.install-mode == 'noneditable' && !github.event.pull_request
        shell: bash
        run: |
          echo "_pip_install_ref=${{ github.ref }}" >> $GITHUB_ENV
      - name: Install (noneditable)
        if: matrix.install-mode == 'noneditable'
        env:
          _pip_install_url: ${{ format('{0}/{1}', github.server_url, github.repository) }}
        run: |
          pip install "${_pip_install_url}@${_pip_install_ref}"
      - name: Set up IDAES solvers
        run: |
          idaes get-extensions --verbose
      - name: Run pytest
        run: |
         pip install pytest  # ensure pytest is installed (should do nothing if already present from requirements-dev.txt
          pytest --pyargs watertap_contrib.reflo
